language: c

arch:
#  - amd64
#  - arm64 
#  - ppc64le
  - s390x 

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - ./turbobench -eCI turbobench   

matrix:
  include:
    - name: windows-mingw-w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
        - ./turbobench -eCI turbobench.exe    

    - name: apple-macOS-xcode
      os: osx

