language: c

arch:
  - amd64
  - arm64 
  - ppc64le
  - s390x 

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make STATIC=1
  - ./turbobench -eCI turbobench  

matrix:
  include:
#    - name: linux-s390x-gcc
#      os: linux
#      arch: s390x 
#      compiler: gcc
#      script: 
#        - make
#        - ./turbobench -eCI turbobench

#    - name: linux-s390x-clang
#      os: linux
#      arch: s390x 
#      compiler: clang
#      script: 
#        - make
#        - ./turbobench -eMEMCPY turbobench

    - name: windows-mingw-w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make STATIC=1
        - ./turbobench -eCI turbobench.exe    

    - name: apple-macOS-xcode
      os: osx

  exclude:
      arch: s390x 
      compiler: clang


