language: c

arch:
# - amd64
  - arm64 
  - ppc64le
  - s390x 

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make 
#  - ./turbobench -eCI -v0 turbobench  
#  - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
#  - ./turbobench -eCI -v0 csrc  

matrix:
  include:
    - name: amd64-linux-gcc
      arch: amd64
      compiler: gcc
      script:
        - make
        - ./turbobench -eCI2 -v0 turbobench  
        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
#        - ./turbobench -eCI2 -v0 csrc  

    - name: amd64-linux-clang
      arch: amd64 
      compiler: clang
      script:
        - make
#        - ./turbobench -eCI2 -v0 turbobench  
#        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > csrc
#        - ./turbobench -eCI2 -v0 csrc  

    - name: amd64-windows-mingw64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
#        - ./turbobench -eCI2 -v0 turbobench.exe    

    - name: amd64-MacOs-xcode
      os: osx
      arch: amd64 

  exclude:
      arch: s390x 
      compiler: clang

