language: c

arch:
  - amd64
  - arm64 
  - ppc64le
  - s390x 

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - find . -type f -exec cat {} + >x
  - ./turbobench -eCI x  

matrix:
  include:

    - name: windows-mingw-w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
        - ./turbobench -eCI turbobench.exe    

    - name: apple-macOS-xcode
      os: osx

  exclude:
      arch: s390x 
      compiler: clang


