language: c

arch:
  - amd64
  - arm64 
  - ppc64le
  - s390x 

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - ./turbobench -eFAST turbobench   

matrix:
  include:
    - name: windows-mingw-w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
        - ./turborc -e0 turborc   

    - name: apple-macOS-xcode
      os: osx

