language: c

arch:
# - amd64
  - arm64 
  - ppc64le
  - s390x 

compiler: 
  - gcc
  - clang

branches:
  only:
    - master 

script:
  - make
  - ./turbobench -eCI -v0 turbobench  
  - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > data
  - ./turbobench -eCI -v0 data  

matrix:
  include:
    - name: linux-amd64-gcc
      arch: amd64
      compiler: gcc
      script:
        - make
        - ./turbobench -eCI2 -v0 turbobench  
        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > data
        - ./turbobench -eCI2 -v0 data  

    - name: linux-amd64-clang
      arch: amd64 
      compiler: clang
      script:
        - make
        - ./turbobench -eCI2 -v0 turbobench  
        - find . -name '*.c' -o -name '*.cpp' -o -name '*.h' -exec cat {} \; > data
        - ./turbobench -eCI2 -v0 data  

    - name: windows-amd64-mingw_w64
      os: windows
      arch: amd64 
      script: 
        - mingw32-make
        - ./turbobench -eCI -v0 turbobench.exe    

    - name: apple-macOS-xcode
      os: osx

  exclude:
      arch: s390x 
      compiler: clang


